query GET_MENU_BY_LOCATION($location: MenuLocationEnum) {
  menu: menus(where: {location: $location}) {
    edges {
      node {
        menuItems(where: {parentId: 0}) {
          edges {
            node {
              ...menuItem
              childItems {
                edges {
                  node {
                    ...menuItem
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

fragment menuItem on MenuItem {
  label
  relativeUrl
  url
  target
}
