#import "./Fragments/PageContent.gql"
#import "./Fragments/ImageHero.gql"

query GET_FRONT_PAGE($pageId: ID!) {
  page(id: $pageId, idType: DATABASE_ID) {
    ...pageContent
    servicesGroup {
      servicesLabel
      services {
        title
        usps {
          text
        }
        link {
          target
          title
          url
          relativeUrl
        }
      }
      servicesImage {
        ...imageHero
      }
    }
  }
}
