#import "./Fragments/PageContent.gql"
#import "./Fragments/ImageArchive.gql"

query GET_WAY_WE_WORK_PAGE_BY_URI($pageId: ID!) {
  page(id: $pageId, idType: DATABASE_ID) {
    ...pageContent
    wayWeWorkGroup {
      wayWeWork {
        text
        title
        image {
          ...imageArchive
        }
      }
    }
  }
}
