#import "./Fragments/PageContent.gql"
#import "./Fragments/ImageArchive.gql"

query GET_TEACHERS_PAGE_BY_URI($pageId: ID!) {
  page(id: $pageId, idType: DATABASE_ID) {
    ...pageContent
    employersGroup {
      employers {
        bio
        facebook
        fieldGroupName
        linkedin
        name
        twitter
        image {
          ...imageArchive
        }
      }
    }
    videosGroup {
      video1
      video2
    }
  }
}
