#import "./Fragments/ImageArchive.gql"

query GET_POSTS($first: Int, $after: String, $notIn: [ID]) {
  posts(first: $first, after: $after, where: { notIn: $notIn }) {
    pageInfo {
      hasNextPage
      endCursor
      hasPreviousPage
      startCursor
    }
    edges {
      node {
        title
        excerpt
        featuredImage {
          node {
            ...imageArchive
          }
        }
        databaseId
        title
        date
        slug
      }
    }
  }
}
