#import "./Fragments/ImageArchive.gql"
#import "./Fragments/ImageHero.gql"

query getSiteDetails {
  siteDetails {
    heroImageGroup {
      image {
        ...imageHero
      }
    }
    socialMediaGroup {
      facebook
      instagram
      linkedin
      twitter
    }
    addressesGroup {
      email
      kvk
      phonenumber
      addresses {
        city
        latitude
        longitude
        street
        zipcode
        image {
          ...imageArchive
        }
      }
    }
  }
}
